### ISSUE TITLE
[FEATURE REQUEST] Backport to 1.20.1

### ISSUE THREAD

**Issue by ItoKyoshiro** [thomasglasser/Bundle-Weight-Theres-Four#1]
Not sure if it possible, but would be possible to have this backported to 1.20.1?
Bundle were experimental there but I'm hoping that the implementation of the stack sizes where the same :)

**Comment by thomasglasser** [comment]
Unfortunately, data components don't exist for 1.20.1, which this system relies on, so it would need a rewrite that I don't have the time for.
